---
- name: wireguard VPS
  hosts: cloud
  remote_user: root
  roles:
    - name: nftables
      tags: nftables
    - name: ssh
      tags: ssh
    - role: wireguard
      tags: wireguard
    - role: unbound
      tags: unbound
