---
- name: Linux VPS
  hosts: cloud
  remote_user: root
  roles:
    - name: nftables
      tags: nftables
    - name: ssh
      tags: ssh
    - role: wireguard
      tags:
        - wireguard
        - ssh
        - nginx
    - role: unbound
      tags: unbound
    - role: certbot
      tags:
        - certbot
        - nginx
    - role: nginx
      tags:
        - nginx
        - certbot
