---
- name: Linux VPS
  hosts: cloud
  remote_user: root
  roles:
    - name: nm
      tags: nm
    - name: nftables
      tags: nftables
    - name: ssh
      tags: ssh
    - name: wireguard
      tags:
        - wireguard
        - ssh
        - nginx
    - name: unbound
      tags:
        - unbound
        - nginx
    - name: certbot
      tags:
        - certbot
        - nginx
    - name: nginx
      tags:
        - nginx
        - certbot
    - name: squid
      tags:
        - unbound
        - squid
