---
- name: Install unbound
  package:
    name: unbound
    state: present

- name: Deploy unbound configuration template
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    mode: 0644
  register: unbound_config

- name: Enable unbound service
  service:
    name: unbound
    enabled: yes

- name: Restart unbound service on changes
  service:
    name: unbound
    state: restarted
  when: unbound_config.changed
