---
- name: Deploy sshd_config configuration template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
  register: sshd_config

- name: Deploy /root/authorized_keys
  template:
    src: root_authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    mode: 0600

- name: Reload sshd service on changes
  service:
    name: sshd
    state: reloaded
  when: sshd_config.changed
