---
- name: Install nftables
  package:
    name: nftables
    state: present

- name: Deploy nftables configuration template
  template:
    src: ansible.nft.j2
    dest: /etc/nftables/ansible.nft
    mode: 0644
  register: nftables_config

- name: Include ansible.nft in sysconfig
  lineinfile:
    path: /etc/sysconfig/nftables.conf
    regexp: '^include "/etc/nftables/ansible.nft"$'
    line: 'include "/etc/nftables/ansible.nft"'

- name: Check ansible.nft validity
  command: nft --check --file /etc/nftables/ansible.nft
  register: nftables_check_config

- name: Enable nftables service
  service:
    name: nftables
    enabled: yes

- name: Restart nftables service on changes
  service:
    name: nftables
    state: restarted
  when: nftables_config.changed
