---
- name: Apply kernel hardening sysctls
  ansible.builtin.command:
    cmd: /usr/sbin/sysctl --load=/etc/sysctl.d/99-kernel-hardening.conf

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
