---
- name: Install squid
  ansible.builtin.dnf:
    name: squid
    state: present

- name: Deploy squid.conf
  ansible.builtin.template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: '0644'
  register: squid_conf

- name: Enable squid service
  ansible.builtin.systemd:
    name: squid
    enabled: true

- name: Restart squid if config changed
  ansible.builtin.systemd:
    name: squid
    state: restarted
  when: squid_conf.changed
