---
- name: Install wireguard-tools
  package:
    name: wireguard-tools
    state: present

- name: Deploy wireguard configuration template
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0600
  register: wireguard_config

- name: Enable wg-quick@wg0 service
  service:
    name: wg-quick@wg0
    enabled: yes

- name: Restart wg-quick@wg0 service on changes
  service:
    name: wg-quick@wg0
    state: restarted
  when: wireguard_config.changed

- name: Allow wireguard traffic via firewalld
  firewalld:
    zone: FedoraServer
    port: "{{wireguard.listen_port}}/udp"
    state: enabled
    permanent: true
    immediate: true

- name: Create wg-quick@wg0.service systemd override directory
  file:
    owner: root
    group: root
    mode: 0755
    path: /etc/systemd/system/wg-quick@wg0.service.d
    state: directory

- name: Create wg-quick@wg0.service systemd override config
  template:
    src: systemd_override.conf.j2
    dest: /etc/systemd/system/wg-quick@wg0.service.d/systemd_override.conf
    mode: 0644
  register: systemd_override_config

- name: systemd daemon-reload on override changes
  systemd_service:
    daemon_reload: true
  when: systemd_override_config.changed


